import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Montserrat } from 'next/font/google';
import Head from "next/head"; // Importing Head from Next.js
import Features from "./components/Features";
const montserrat = Montserrat({ subsets: ['latin'], weight: ['400', '700'] });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Policy Sansar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Policy Sansar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/sansar.png" /> {/* Corrected path */}
      </Head>
      <body className={montserrat.className}>
        <Header />
        {children}
        <Features/>
        <Footer />
      </body>
    </html>
  );
}
